CREATE TABLE IF NOT EXISTS Person
(
PersonKey BIGINT PRIMARY KEY AUTO_INCREMENT,
PersonData JSON
);

CREATE TABLE IF NOT EXISTS Game
(
GameKey BIGINT PRIMARY KEY AUTO_INCREMENT,
GameData JSON
);

CREATE TABLE IF NOT EXISTS Vote
(
VoteKey BIGINT PRIMARY KEY AUTO_INCREMENT,
PersonKey BIGINT,
GameKey BIGINT,
VoteNumber INT
);

CREATE TABLE IF NOT EXISTS Suggestion
(
SuggestionKey VARCHAR(2000) PRIMARY KEY,
SuggestionData JSON
);

